### ISSUE TITLE
MeshAgent old glibc

### ISSUE THREAD

**Issue by pczolee** [Ylianst/MeshAgent#19]
Hello.

I try to run the agent on my old CentOS 5.11 (2.6.18-398.el5 #1 SMP Tue Sep 16 20:51:48 EDT 2014 i686 athlon i386 GNU/Linux
), it is not running, because the old glibc (glibc-2.5-123)

# ./meshagent
./meshagent: /lib/libc.so.6: version `GLIBC_2.9' not found (required by ./meshagent)
./meshagent: /lib/libc.so.6: version `GLIBC_2.7' not found (required by ./meshagent)
./meshagent: /lib/libc.so.6: version `GLIBC_2.11' not found (required by ./meshagent)

Can you compile me a version which is running? Or help me how to do it?

Thank you

**Comment by krayon007** [comment]
I'll have to build a CentOS 5.11 image, as the oldest machine I have is Ubuntu 9, which appears to still have a newer libc than you...

In the meantime, it should be easy to compile yourself. Tho you'll need to compile  openssl and turbo-jpeg. The instructions for doing that, is in the makefile.  I'll try to build the image tonight, and see if I can post a link here tomorrow...

**Comment by krayon007** [comment]
32 bit?

**Comment by krayon007** [comment]
This might take a while. CentOS 5.11 is very old, so I'm having a very hard time compiling this for you, because all the tools are out of date. I can't connect to any websites, because openssl is extremely old. In order to compile a newer OpenSSL, I need to also recompile Perl, the current OpenSSL requires a newer Perl. Likewise, GIT doesn't work, because GIT can't connect to any repos because OpenSSL is too old. I finally got OpenSSL, Perl, and GIT compiled, but now it's complaining that CURL is too old. But while trying to get that to work, I broke the package manager, because apparently YUM doesn't work with newer OpenSSL, so now I have to start all over again, because I didn't create a snapshot....

**Comment by pczolee** [comment]
Thank you very much for your helping. Yes this is a very old system, but this is in production so there is no way to update. It is 32bit. If i can help anything let me know. If you can give me the complied libs (what you made and i need to complie it), than i can make regular update when a new version is coming (maybe there are some other people who need it).

**Comment by krayon007** [comment]
I got the agent compiled on CentOS 5.11, just trying to figure out why KVM isn't working. It works on CentOS 6 but not 5.11 for some reason...

I pushed into git the OpenSSL and turbojpeg libraries I compiled. I also updated the makefile, because apparently the GCC on CentOS 5.11 doesnt understand one of the flags I was using, So I added a LEGACY_LD build flag.

I'll post something here later today, so you can test it out. I noticed /sbin isn't on the path for CentOS 5.11 too, so I had to tweak how I was finding libraries, but I didn't check that in yet.

**Comment by krayon007** [comment]
Ok, I got it all working on CentOS 5.11, including KVM...

You'll either need to drop the binary into your server, or you need to disable auto-update on the client side, otherwise when you start it, it will most likely auto-update to the version on the server, which won't work on CentOS 5.11.

[Link to binary](https://alt.meshcentral.com/userfiles/byroe/meshagent_x86)

**Comment by krayon007** [comment]
By the way, everything is checked into GIT, so if you pull the agent repo, and you needed to build on CentOS 5.11, you can do:

make linux ARCHID=5 FSWATCH_DISABLE=1 LEGACY_LD=1

You'll need to make sure you have the development libraries installed for X and jpeg:
sudo yum install libX11-devel libXtst-devel libXext-devel libjpeg-devel

**Comment by pczolee** [comment]
This is fantastic! You are a genius! Thank you so much for you hard work. 

God bless you!

**Comment by pczolee** [comment]
I'm sorry for my stupid question, but how can I disable auto update?

**Comment by pczolee** [comment]
Is someone else need I found how to disable auto update (in the issue #4):

./meshagent_x86-64 modules/dbTool.js put disableUpdate=1
to turn off updates and
./meshagent_x86-64 modules/dbTool.js delete disableUpdate
to turn it back on.

**Comment by krayon007** [comment]
The easiest way is to edit the .msh file and put:
disableUpdate=1
In the last line.

To reenable, put:
disableUpdate=

In it instead.

**Comment by krayon007** [comment]
I noticed that user-consent and notifications aren't working on CentOS 5.11, so I'll take a look at that when I get back in the office. Looks like I'll be able to get the consent-dialog working, but the notification doesn't seem to work with the built in utility.

**Comment by krayon007** [comment]
If you repull the binary from the link above (or do another pull on the repo), user-consent and notifications will work correctly on CentOS 5.11

**Comment by pczolee** [comment]
Thank you. I'll update it now.

**Comment by krayon007** [comment]
Make sure you add /sbin to your path. CentOS 5 doesn't add that by default. A bunch of stuff doesn't work if that isn't set...

**Comment by krayon007** [comment]
I'm modifying the code to be able to auto add that if it's not set for the agent process.

**Comment by pczolee** [comment]
Thank you so much!

**Comment by pczolee** [comment]
I tried now to build in raspbian 7.11, which is pretty old (this is an rpi1), it have glibc 2.13, kernel 4.19.66. Installed what is in the makefile, but cannot build, here is the error:

Duktape_WritableStream.o microscript/ILibDuktapeModSearch.o microscript/ILibDuktape_WebRTC.o microscript/ILibDuktape_SimpleDataStore.o microscript/ILibDuktape_GenericMarshal.o microscript/ILibDuktape_fs.o microscript/ILibDuktape_SHA256.o microscript/ILibduktape_EventEmitter.o microscript/ILibDuktape_EncryptionStream.o microscript/ILibDuktape_Polyfills.o microscript/ILibDuktape_Dgram.o microscript/ILibDuktape_ScriptContainer.o microscript/ILibDuktape_MemoryStream.o microscript/ILibDuktape_NetworkMonitor.o microscript/ILibDuktape_ChildProcess.o microscript/ILibDuktape_HECI.o microscript/ILibDuktape_HttpStream.o microscript/ILibDuktape_Debugger.o meshcore/KVM/Linux/linux_kvm.o meshcore/KVM/Linux/linux_events.o meshcore/KVM/Linux/linux_tile.o meshcore/KVM/Linux/linux_compression.o meshcore/agentcore.o meshconsole/main.o meshcore/meshinfo.o -Lopenssl/libstatic/linux/armhf -l:lib-jpeg-turbo/linux/armhf/libturbojpeg.a -L. -lpthread -ldl -lutil -lm  -lssl -lcrypto -lrt -o meshagent_armhf
openssl/libstatic/linux/armhf/libcrypto.a(uid.o): In function `OPENSSL_issetugid':
uid.c:(.text+0x8): undefined reference to `getauxval'
collect2: ld returned 1 exit status
make[1]: *** [meshagent_armhf] Error 1
make[1]: Leaving directory `/root/temp/MeshAgent-master'
make: *** [linux] Error 2

How to solve this?
Thanks

**Comment by pczolee** [comment]
No, I didn't, I'll try to do it first. Anyway I found that the "meshagent_armhf2" binary working fine with old glibc.
And (one more information ;) ) I built it successful in Centos 5.11!

Thanks a lot

**Comment by pczolee** [comment]
Hi @krayon007 
I tried to build the actual version, but in won't work :(

> shinfo.o -Lopenssl/libstatic/linux/x86 lib-jpeg-turbo/linux/x86/libturbojpeg.a -L. -lpthread -ldl -lutil -lm -no-pie  -lssl -lcrypto -lrt -z noexecstack -z relro -z now -o meshagent_x86
gcc: unrecognized option '-no-pie'
openssl/libstatic/linux/x86/libcrypto.a(v3_utl.o): In function `ipv6_cb':
v3_utl.c:(.text+0x2f0): undefined reference to `__isoc99_sscanf'
openssl/libstatic/linux/x86/libcrypto.a(v3_utl.o): In function `a2i_ipadd':
v3_utl.c:(.text+0x240e): undefined reference to `__isoc99_sscanf'
collect2: ld returned 1 exit status
make[1]: *** [meshagent_x86] Error 1
make[1]: Leaving directory `/home/Mesh/MeshAgent-master'
make: *** [linux] Error 2

Can you help me, why? Centos 5.11 32bit

Thanks

**Comment by krayon007** [comment]
I recompiled the 32 bit x86 linux openssl .a files on CentOS 5.11, so it should work for you now, if you repull the tip and recompile. When it was updated to 1.1.1g, my CentOS 5.11 version was overwritten with a build from a newer libc.

**Comment by pczolee** [comment]
> I recompiled the 32 bit x86 linux openssl .a files on CentOS 5.11, so it should work for you now, if you repull the tip and recompile. When it was updated to 1.1.1g, my CentOS 5.11 version was overwritten with a build from a newer libc.

Thank you very much. Now built successfully ;)

**Comment by knkumar93** [comment]
Hi @krayon007,

I am above mentioned points to compile mesh agent in CentOS 5.11 but getting below error. Your advice would be helpful to proceed further.

/opt/meshagent/MeshAgent-MeshCentral_v0.7.65/microstack/ILibParsers.h:329: undefined reference to `__sync_bool_compare_and_swap_4'

Detailed error: [compile-error.txt](https://github.com/Ylianst/MeshAgent/files/9632233/compile-error.txt)

Tried with latest version (1.0.75) also but getting same error.

**Comment by krayon007** [comment]
I have a cent is 5.11 system. Are you running 32 bit or 64 bit? I know I had to compile openssl using CentOS/5.11 because the glibc in it is older than the Ubuntu 10 system that ylian uses to build most of the agents. I usually manually check in the 5.11 openssl library if it gets overwritten when we check in openssl updates. My CentOS/5.11 is 32 bit. I'll check to see what openssl is checked in GIT. If you need a 64 bit version, I'll send you the library. I know the glibc in 5.11 is missing some of the thread synchronization primitives that we wrote workarounds for, so that's why I didnt usually build a 64 bit version.

**Comment by knkumar93** [comment]
Hi @krayon007,

My build machine is CentOS 5.11 64bit machine. But I am trying to build 32bit binary using ARCHID=5 option. But getting the mentioned error.

**Comment by krayon007** [comment]
For CentOS/5.11 you also need to set the following flags when building:

`make linux ARCHID=5 FSWATCH_DISABLE=1 LEGACY_LD=1`

**Comment by knkumar93** [comment]
Hi @krayon007.

Thanks with above command I am able to build, however I am getting segmentation fault error, when I try to run it. Below steps done.

Placed built meshagent_x86 inside node_modules\MeshCentral\agents folder
Downloaded Linux X86-32 version of binary installer from mesh portal.
Placed in linux machine (same CentOS 5.11) 
and then 
`chmod +x ./meshagent`
then, launched it with 
`./meshagent`
Getting segmentation fault error.

**Comment by krayon007** [comment]
Does the following work, after you download said binary installer?
`./meshagent -help`
`./meshagent -connect`

**Comment by knkumar93** [comment]
Hi @krayon007 ,

Please ignore my previous reply. I was confused with different Ubuntu machine build.

In Cent OS 5.11 by using option which you suggested, I was still getting same error which I mentioned earlier. 

`/opt/meshagent/MeshAgent-MeshCentral_v0.7.65/microstack/ILibParsers.h:329: undefined reference to '__sync_bool_compare_and_swap_4'`

Later did some research and found a suggestion [here](https://gcc.gcc.gnu.narkive.com/D7xlysCt/sync-bool-compare-and-swap#post5). Tried passing additional option -march=i686 in makefile in line number 284, then the compilation got succeeded. I can use this to run in RHEL 5.9 machine. I can also run same in Ubuntu 16.04 machine.

`CC = gcc -m32 -march=i686`

Now I am Able to access terminal, file transfer, but Desktop tab is not appearing.

**Comment by MrGrumps** [comment]
Good day all,

Struggling here to build MeshAgent 1.1.0 on CentOS 5.11 32-bit, getting the below:
`/root/Source_Codes/MeshAgent-MeshCentral_v1.1.0/microstack/ILibParsers.h:333: undefined reference to `__sync_bool_compare_and_swap_4'
/root/Source_Codes/MeshAgent-MeshCentral_v1.1.0/microstack/ILibParsers.h:333: undefined reference to `__sync_bool_compare_and_swap_4'
/root/Source_Codes/MeshAgent-MeshCentral_v1.1.0/microstack/ILibParsers.h:333: undefined reference to `__sync_bool_compare_and_swap_4'
/root/Source_Codes/MeshAgent-MeshCentral_v1.1.0/microstack/ILibParsers.h:333: undefined reference to `__sync_bool_compare_and_swap_4'
/root/Source_Codes/MeshAgent-MeshCentral_v1.1.0/microstack/ILibParsers.h:333: undefined reference to `__sync_bool_compare_and_swap_4'
microstack/ILibAsyncSocket.o:/root/Source_Codes/MeshAgent-MeshCentral_v1.1.0/microstack/ILibParsers.h:333: more undefined references to `__sync_bool_compare_and_swap_4' follow
`

I tried all the suggestions on this forum but still can't it to compile. Does someone perhaps still have a working binary available that you could perhaps send me? I am missing something but don't know what and brain is fried.
