### ISSUE TITLE
Compile error on debian 10

### ISSUE THREAD

**Issue by guerby** [Ylianst/MeshAgent#47]
Hi

Current HEAD doesn't compile on Debian 10 with GCC 8.3.0:

```
make ARCH=6
...
gcc -DJPEGMAXBUF=0 -DMESH_AGENTID=6 -std=gnu99 -g -Wall -D_POSIX -DMICROSTACK_PROXY  -DILibChain_WATCHDOG_TIMEOUT=6000000 -fno-strict-aliasing -I. -Iopenssl/include -Imicrostack -Imicroscript -Imeshcore -Imeshconsole -DDUK_USE_DEBUGGER_SUPPORT -DDUK_USE_INTERRUPT_COUNTER -DDUK_USE_DEBUGGER_INSPECT -DDUK_USE_DEBUGGER_PAUSE_UNCAUGHT -D_LINKVM -DMICROSTACK_TLS_DETECT -O3 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fstack-protector -fno-strict-aliasing   -c -o meshcore/agentcore.o meshcore/agentcore.c
meshcore/agentcore.c:3952:1: error: unknown type name ‘BOOL’; did you mean ‘BIO’?
 BOOL MeshAgent_PidWaiter(void *chain, HANDLE h, ILibWaitHandle_ErrorStatus status, void* user)
 ^~~~
 BIO
meshcore/agentcore.c:3952:49: error: unknown type name ‘ILibWaitHandle_ErrorStatus’; did you mean ‘ILibWebServer_Status’?
 BOOL MeshAgent_PidWaiter(void *chain, HANDLE h, ILibWaitHandle_ErrorStatus status, void* user)
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                                 ILibWebServer_Status
make[1]: *** [<builtin>: meshcore/agentcore.o] Error 1
make[1]: Leaving directory '/home/tmp/git/MeshAgent'
make: *** [makefile:511: linux] Error 2
```

I applied the following (probably incorrect) patch to be able to build the agent, no other error.

```
diff --git a/meshcore/agentcore.c b/meshcore/agentcore.c
index 917681e..11ac03e 100644
--- a/meshcore/agentcore.c
+++ b/meshcore/agentcore.c
@@ -3949,11 +3949,11 @@ void MeshAgent_AgentInstallerCTX_Finalizer(duk_context *ctx, void *user)
        }
 }
 
-BOOL MeshAgent_PidWaiter(void *chain, HANDLE h, ILibWaitHandle_ErrorStatus status, void* user)
+void MeshAgent_PidWaiter(void *chain, HANDLE h, int status, void* user)
 {
        ILibStopChain(chain);
-       return(FALSE);
 }
+
```

**Comment by krayon007** [comment]
it's supposed to be:
make linux ARCHID=6

**Comment by guerby** [comment]
Yes sorry, I checked and I used `make linux ARCHID=6` in command line but retyped it wrong from memory in the github issue.

**Comment by krayon007** [comment]
I pushed one more commit... You caught me in the middle of testing, and didn't check in the missing #ifdef for windows tho... If you pull again it should work.

**Comment by guerby** [comment]
It now compiles, thanks!
